### ISSUE TITLE
Ability to skip if more than 1/3 or 1/2 people in voice say the ;;skip command

### ISSUE THREAD

**Issue by Hunors5000** [Frederikam/FredBoat#56] opened 2017-01-16 17:06 UTC
Basically i would like the mode so instead of anyone being able to skip without question I would like a feature that will skip a song only if more than half of the people in voice type ;;skip, Perhaps make it into two different modes?

**Comment by Frederikam** [comment] 2017-01-16 19:09
This is basically a duplicate of https://github.com/Frederikam/FredBoat/issues/26 I would guess. My idea is to add a server setting where only moderators can forcefully skip (if they choose to).

**Closed** 2017-01-18 14:17 UTC
