### ISSUE TITLE
please make ;;skip require a vote or something

### ISSUE THREAD

**Issue by TheSqrtMinus1** [Frederikam/FredBoat#62] opened 2017-01-21 14:34 UTC
In a large server of >500 people when even 10 people get in a music bot chat it can become quite chaotic when people keep skipping other's songs. If you could add a feature where it requires like at least half of the people in the voice chat that the bot is currently in to type ";;skip" that would be great.

**Comment by Frederikam** [comment] 2017-01-21 14:38
This is a duplicate of https://github.com/Frederikam/FredBoat/issues/26

This idea is already high on my priorities list and may be by next goal after next update is shipped.

**Closed by Frederikam** 2017-01-21 14:38 UTC

**Comment by TheSqrtMinus1** [comment] 2017-01-21 14:59
oh ok thanks
