### ISSUE TITLE
[Cutting Edge] Help command's response is incorrect.

### ISSUE THREAD

**Issue by OtterBoops** [Frederikam/FredBoat#511] opened 2018-07-19 12:48 UTC
Steps to reproduce:
1. Enable DMs from Server Members
2. Issue `<<help` command.

Expected result:
The bot responds with `Documentation has been sent to your DMs!`

Actual result:
The bot responds with `Could not send documentation to your DMs. Please check that you don't have them disabled!`, even though the message was delivered successfully.

**Comment by Frederikam** [comment] 2018-07-19 12:52
Unable to repro 
![image](https://user-images.githubusercontent.com/2582617/42943530-4ffae330-8b63-11e8-9af0-672563e22df8.png)

Check that this works with the regular FredBoat in the same server

**Comment by napstr** [comment] 2018-07-19 12:55
The issue not that you get the help, the issue is that it says it could not DM you, despite the DM being successful.

**Comment by Frederikam** [comment] 2018-07-19 12:56
Fair enough, I didn't see the response, which is indeed wrong for me as well.

**Comment by Frederikam** [comment] 2018-07-19 13:58
Should be fixed, please verify

**Comment by Frederikam** [comment] 2018-07-19 14:05
:ok_hand: 
![image](https://user-images.githubusercontent.com/2582617/42947387-7e470480-8b6d-11e8-8abe-32151f01b179.png)

**Closed by Frederikam** 2018-07-19 14:05 UTC
Labels: FredBoat Cutting Edge
