### ISSUE TITLE
Limit on length of songs

### ISSUE THREAD

**Issue by RealKC** [Frederikam/FredBoat#226] opened 2017-07-21 13:20 UTC
A command or `;;config` option to set a limit on the length of songs.

**Comment by Frederikam** [comment] 2017-07-21 13:21
I'm thinking the ADMIN permission would bypass this. Thoughts?

**Comment by RealKC** [comment] 2017-07-21 13:26
Yes, I think it should.

**Comment by napstr** [comment] 2017-08-22 13:48
Closing as it's a duplicate of #39

**Closed by napstr** 2017-08-22 13:48 UTC
Labels: Beginner
