### ISSUE TITLE
Handle markdown in externally generated content

### ISSUE THREAD

**Issue by napstr** [Frederikam/FredBoat#92] opened 2017-03-12 16:49 UTC
Some things that FredBoat displays to users can contain markdown syntax and fuck around with how the bots output looks:

Example:

![image](https://cloud.githubusercontent.com/assets/6048348/23833842/0abb111a-074c-11e7-8b89-adee9ce7b6ad.png)

Song names, playlist names, user names. Anything I'm missing?
Need to either strip external content of markdown tags, or maybe find an acceptable way to display it in `code` tags.

**Comment by Frederikam** [comment] 2017-03-12 16:54
This is something I have been meaning to do for quite a while. It can be solved by escaping markdown symbols with `\`

**Comment by Nanabell** [comment] 2017-06-04 14:39
To bring this up again, since we talked about preventing pings like @everyone or @here or just userpings. this is basically the same case here. Escaping @ # 
But iirc we would need to replace all sendMessage's

**Comment by BadJukeBox** [comment] 2017-10-01 04:40
Hey! I'd like to take a go at this one if you don't mind. That being said I'm a bit curious as to what the issue is, are you referring to the way that the lines are different fonts  or is that intended. Sorry if i'm missing something here. As well thank you for putting a 'how to contribute' post for us new guys :)

**Comment by napstr** [comment] 2017-10-01 09:38
[Discord supports markdown for formatting posts.](https://support.discordapp.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-), and we make use of that to format our output nicely, example:
![image](https://user-images.githubusercontent.com/6048348/31053403-9f524c54-a69c-11e7-9885-e5bc073f263b.png)

Notice the songname and username and a few other information being bold or in code tags for better readability. However, we are using user generated content (the nickname for example), and that might contain formatting characters. Watch what happens to the same list of songs if I change my nickname:
![image](https://user-images.githubusercontent.com/6048348/31053418-04879dea-a69d-11e7-98fc-ef1b0065e63a.png)

**Comment by Frederikam** [comment] 2017-10-02 08:09
To elaborate, it is possible to escape markdown like so:


\\\_\\\*\\\*Napster\\\_

Which generates:

\_\*\*Napster\_

So simply preface any \*\_\~ with \\

**Comment by jnkdev** [comment] 2017-10-14 20:17
@BadJukeBox how's your progress on this? I'd like to try solve this too if you don't mind.

**Comment by BadJukeBox** [comment] 2017-10-14 22:43
@jnkdev Unfortunately, midterm season is in full swing for me so I haven't been able to anything that I actually want to. You can take a crack at it if you want, I play to try sometime this week myself!

**Comment by Shredder121** [comment] 2017-10-15 12:50
If necessary I can also point you at a guava utility called `Escapers`.
You could build a `MARKDOWN_ESCAPER` in `TextUtils` and add an `escapeMarkdown(String)` method.

**Comment by Shredder121** [comment] 2017-10-17 19:23
What's the progress on this? :>

**Comment by napstr** [comment] 2017-11-01 22:51
Part of this was done in #367 
Keeping this open because the rest of the code needs to be checked for possible usages of the markdown escaping (commands + player classes probably contain 99% of the cases where escaping user input is a good idea).

**Comment by napstr** [comment] 2017-11-18 16:17
33882286fdd5ebf8c13868a394fa3c3d068f2dbc did some progress on this

**Comment by napstr** [comment] 2018-01-20 11:27
Piggybacking on this, external content also needs to be stripped from possible mentions. Methods for escaping and defusing mentions already exist in the TextUtils.

**Comment by napstr** [comment] 2018-01-20 13:29
3a613192fa5bf9d2be026670f2d43d95c5d125ed
0865183d3850e75f661ad5fa59f0c84f9a85dccc
more progress on this but maybe not everything
I looked for direct title and author references accross the codebase.

**Comment by Frederikam** [comment] 2018-07-27 15:20
I am not aware of any places where this is not fixed, so I am closing.

**Closed by Frederikam** 2018-07-27 15:20 UTC
Labels: Beginner, Hacktoberfest
