### ISSUE TITLE
Exception in thread "main" org.json.JSONException: JSONObject["shards"] not found.

### ISSUE THREAD

**Issue by flaxues** [Frederikam/FredBoat#75] opened 2017-02-10 21:10 UTC
Hello

I'm having a problem with starting up the bot. I configured everything. But When I run the java on Ubuntu I'm getting this error:
```
[21:09:14] [ INFO ] [FredBoat] Invalid scope, defaulting to scopes 0x111
[21:09:14] [ INFO ] [FredBoat] Starting with scopes:
	Main: true
	Music: true
	Self: true
[21:09:14] [ INFO ] [FredBoat] JDA version:	3.0.BETA2_121
[21:09:14] [ INFO ] [FredBoat] Using lavaplayer nodes
[21:09:14] [ INFO ] [FredBoat] Determined distribution: PATRON
Exception in thread "main" org.json.JSONException: JSONObject["shards"] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at org.json.JSONObject.getInt(JSONObject.java:598)
	at fredboat.util.DiscordUtil.getRecommendedShardCount(DiscordUtil.java:113)
	at fredboat.FredBoat.initBotShards(FredBoat.java:210)
	at fredboat.FredBoat.main(FredBoat.java:174)
```

I have no clue on how to fix this...

**Comment by Frederikam** [comment] 2017-02-10 21:13
This exception occurs when either your supplied token is invalid, or the token belongs to a user account.

**Comment by flaxues** [comment] 2017-02-10 21:17
Do I need to use the "client secret" ?

**Comment by Frederikam** [comment] 2017-02-10 21:19
No, the client secret is currently unused. Perhaps the problem is that you
are not supplying the token in the right location. Should be `token.patron`.

**Comment by flaxues** [comment] 2017-02-10 21:47
That was the problem...

But when I try to play music I get this:
```
Exception in thread "JDA AudioConnection Guild: 257923254147219456 Ready Thread" java.lang.UnsatisfiedLinkError: Required library at /natives/linux-arm/libudpqueue.so was not found
	at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.extractLibrary(NativeLibLoader.java:93)
	at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.load(NativeLibLoader.java:77)
	at com.sedmelluq.discord.lavaplayer.udpqueue.natives.UdpQueueManagerLibrary.getInstance(UdpQueueManagerLibrary.java:13)
	at com.sedmelluq.discord.lavaplayer.udpqueue.natives.UdpQueueManager.<init>(UdpQueueManager.java:26)
	at com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendFactory.initialiseQueueManager(NativeAudioSendFactory.java:31)
	at com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendFactory.addInstance(NativeAudioSendFactory.java:58)
	at com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendSystem.start(NativeAudioSendSystem.java:22)
	at net.dv8tion.jda.core.audio.AudioConnection.setupSendSystem(AudioConnection.java:225)
	at net.dv8tion.jda.core.audio.AudioConnection.access$200(AudioConnection.java:47)
	at net.dv8tion.jda.core.audio.AudioConnection$1.run(AudioConnection.java:123)
```

**Comment by flaxues** [comment] 2017-02-10 21:47
I'm running Java 8 JDK

**Comment by Frederikam** [comment] 2017-02-10 21:55
You are running the bot on an `arm-linux` system. This is actually quite strange as I added a special case for simply `arm` architecture. This is caused by a feature that allows for constant sending even when the JVM is stopped by garbage collection.

I have just committed a patch on the `development` branch that disables this optional JDA feature when running `arm-linux`. Try cloning that branch instead (with `--recursive` to include submodules).

**Comment by flaxues** [comment] 2017-02-10 22:07
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running fredboat.feature.I18nTest
[22:06:52] [ INFO ] [I18n] Loaded 21 languages: {it_IT=[Italiano}, ru_RU=[???????}, ro_RO=[Rom?n?}, da_DK=[Dansk}, tr_TR=[T?rk?e}, id_ID=[Bahasa Indonesia}, bg_BG=[????????? ????}, pt_BR=[Portugu?s (Brazil)}, vi_VN=[Ti?ng Vi?t}, fr_FR=[Fran?ais}, he_IL=[?????}, cs_CZ=[?e?tina}, de_DE=[Deutsch}, zh_TW=[????}, ko_KR=[???}, en_US=[English}, en_TS=[Tsundere English}, en_PT=[Pirate English}, es_ES=[Espa?ol}, nl_NL=[Nederlands}, pt_PT=[Portugu?s}}
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.675 sec
[22:06:52] [ INFO ] [BotTest] Loading test credentials from TEST_CONF
org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException; nested exception is java.lang.reflect.InvocationTargetException: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:451)
	at org.json.JSONObject.<init>(JSONObject.java:195)
	at org.json.JSONObject.<init>(JSONObject.java:319)
	at fredboat.Config.<init>(Config.java:71)
	at fredboat.BotTest.<init>(BotTest.java:65)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.maven.surefire.junit.PojoTestSet.<init>(PojoTestSet.java:63)
	at org.apache.maven.surefire.junit.JUnit3Provider.createTestSet(JUnit3Provider.java:107)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:97)
	... 9 more

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.559 s
[INFO] Finished at: 2017-02-10T22:06:52+00:00
[INFO] Final Memory: 29M/69M
[INFO] ------------------------------------------------------------------------
```

**Comment by Frederikam** [comment] 2017-02-10 22:11
Oh yeah, that's something I should get around to fix.

Anyways, you can safely skip tests by appending your `mvn` command with `-DskipTests=true`.

**Comment by flaxues** [comment] 2017-02-10 22:16
It's playing music!

**Comment by flaxues** [comment] 2017-02-10 22:34
It's not a real problem but the bot is saying this: "Playing [0] Say ;;help" 

I suppose [0] is where they title of the had to be?

**Comment by Frederikam** [comment] 2017-02-10 22:37
The number is the current shard id. This isn't really relevant when running just one shard.

Displaying the song title would be impossible without running one shard per guild (which you shouldn't unless you have one or two guilds), which is not what FredBoat was designed.

The status is shard-specific.

**Comment by flaxues** [comment] 2017-02-10 22:39
Ah... Thanks for helping me!

**Closed** 2017-03-09 06:26 UTC
