### ISSUE TITLE
Unable to export a split youtubevideo to hastebin

### ISSUE THREAD

**Issue by Toorero** [Frederikam/FredBoat#468] opened 2018-02-15 16:41 UTC
If you split a youtubevideo like `;;split https://www.youtube.com/watch?v=WU7SGn0MeP0` it won't export it in the correct way to replay it afterwards. Perhaps it would be an option to just export a phrase like `[split] https://www.youtube.com/watch?v=WU7SGn0MeP0` so the bot knows that he should split the video in the moment he imports it.

**Comment by napstr** [comment] 2018-02-15 16:46
Duplicate of #150

**Closed by napstr** 2018-02-15 16:46 UTC
