### ISSUE TITLE
Add an alias command

### ISSUE THREAD

**Issue by Toorero** [Frederikam/FredBoat#467] opened 2018-02-15 16:34 UTC
I would like to see an alias command. So you can just typ `;;alias supercoolplaylist https://www.youtube.com/watch?v=WU7SGn0MeP0` to set the alias. Afterwards you can invoke the play of the alias with `;;playalias supercoolplaylist` so you don't block a song from playing. Some other useful commands to manage the alias-system would be:

- `;;deletealias`

- `;;listalias`

**Comment by napstr** [comment] 2018-02-15 16:39
Duplicate of #168

**Comment by napstr** [comment] 2018-02-15 16:40
Ongoing development here: https://github.com/Frederikam/FredBoat/pull/440

**Closed by napstr** 2018-02-15 16:39 UTC
