### ISSUE TITLE
;;perms command

### ISSUE THREAD

**Issue by TheLMiffy1111** [Frederikam/FredBoat#41] opened 2017-01-04 09:42 UTC
Makes certain commands available only to certain user groups.

**Comment by RealKC** [comment] 2017-01-04 10:53
The Dashboard(#23) will allow you to choose which roles will be able to use certain commands.

**Comment by Frederikam** [comment] 2017-01-04 12:33
How would usage be like?

**Comment by Nanabell** [comment] 2017-01-04 15:59
i would assume ;;perms <Command> <MinRole> 
and minRole is bound to the Discord hierarchy (Position)

**Comment by Frederikam** [comment] 2017-01-05 14:30
I kinda don't like the idea of using command names as keys, since aliases are a thing and some commands do similar things (such as ;;fwd, ;;rew, ;;restart and ;;seek)

Instead, we might want to have groups of permissions. Or both.

Ultimately I would prefer a system that is as close to Discord's system as possible. UI design for the dashboard should also be considered.

**Comment by napstr** [comment] 2017-06-30 13:01
Duplicate of https://github.com/Frederikam/FredBoat/issues/198

**Closed by napstr** 2017-06-30 13:01 UTC
Labels: Needs more info
