### ISSUE TITLE
Buggy Bot behavior under some rare edge case condition

### ISSUE THREAD

**Issue by Nanabell** [Frederikam/FredBoat#301] opened 2017-09-19 16:05 UTC
![image](https://user-images.githubusercontent.com/13600006/30602393-ba9ea4b2-9d64-11e7-9c7a-752aa8aff57d.png)
Aswell as 
- ;;destroy not clearing the queue and just skipping to the next song.
- it seemed to randomly queue a playlist
- ;;stop only says it skips 1 track but can be done infinitely

I obviously know what happened when we tried to investigate this on the server but we should still try to fix this as it might happen to other servers and this is semi-serious

**Comment by napstr** [comment] 2017-09-20 15:52
https://sentry.davinci.sh/fredboat/fredboat/issues/2541/

```
NullPointerException: None
    at fredboat.command.music.info.ListCommand.onInvoke(ListCommand.java:112)
    at fredboat.commandmeta.CommandManager.prefixCalled(CommandManager.java:141)
    at fredboat.event.EventListenerBoat.limitOrExecuteCommand(EventListenerBoat.java:134)
    at fredboat.event.EventListenerBoat.onMessageReceived(EventListenerBoat.java:110)
    at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:402)
...
(14 additional frame(s) were not displayed)

Caught exception while executing a command
```

Is likely caused by a null atc object, which is probably introduced to the sublist due these lines:
https://github.com/Frederikam/FredBoat/blob/8c9f70c2e7520afae24ce85828f7d70c0e268da1/FredBoat/src/main/java/fredboat/audio/player/GuildPlayer.java#L197-199

The lavalink remote player reports it is playing a track, while the GuildPlayers context is null.

**Comment by napstr** [comment] 2018-01-22 08:59
This issue is in a weird spot. It's either solved, or will probably becomes irrelevant with lavalink v2. Closing it for now.

**Closed by napstr** 2018-01-22 08:59 UTC
Labels: Bug
