### ISSUE TITLE
Make it able to repeat an entire playlist

### ISSUE THREAD

**Issue by Raydor** [Frederikam/FredBoat#66] opened 2017-01-27 18:26 UTC
It would be nice to have a command to make the bot repeat a playlist (or a playlist that was created by adding songs 1 by 1) when it finishes.

**Comment by Frederikam** [comment] 2017-01-27 18:28
Duplicate of https://github.com/Frederikam/FredBoat/issues/42

**Closed by Frederikam** 2017-01-27 18:28 UTC
